apiVersion: v1
kind: Service
metadata:
   namespace: tor
   name: tor-gateway-svc
   labels:
      app: tor-gateway
spec:
   type: NodePort
   ports:
   - name: gateway-port
     port: 8088
     targetPort: 8088
     nodePort: 30088
   selector:
        app: tor-gateway

